### ISSUE TITLE
Let application decide when to add CSP http header

### ISSUE THREAD

**Issue by ahouben** [juunas11/aspnetcore-security-headers#12]
First of all, thanks for providing this library, it works fine.

Currently, every response has the CSP header set which is not always desirable. Consider a web application with a mix of MVC/Razor and API controllers where only the MVC/Razor controllers are entry points for client browsers and the API is used by client browsers **and** other API-only clients. Since only browsers know what to do with and how to interpret a CSP header the API clients don't need that header, we could save a few bytes of network traffic.

One possible solution would be to add an extension point at https://github.com/juunas11/aspnetcore-security-headers/blob/4405ac7df969162f76afef5f75dce95dd74f0449/src/Joonasw.AspNetCore.SecurityHeaders/Csp/CspMiddleware.cs#L55 where an application may decide whether to add the CSP header or not.

One approach would be to add an `Events` object with callbacks similar to https://github.com/aspnet/Security/blob/ff9f145a8e89c9756ea12ff10c6d47f2f7eb345f/src/Microsoft.AspNetCore.Authentication.Cookies/Events/CookieAuthenticationEvents.cs to CspOptions. What do you think ?

**Comment by juunas11** [comment]
First of all, thanks for the suggestion!

I think this is a great idea.

In this case we will probably not need the Events object since there is only one event.
A property on the Options class that takes a delegate would probably be enough.

We can pass at least the `HttpContext` to it, and it could return a `Task<bool>` so that if there was a need to do something async, it can be done.

All suggestions are welcome :)
